name: Composer Diff
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '!*'
      - 'composer.lock'
      - 'utils/**/composer.lock'

## This workflow needs the `pull-request` permissions to work
## Refs: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions:
  pull-requests: write
  contents: read
jobs:
  composer-lock-directories:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.parse-working-directories.outputs.directories }}
    steps:
      - name: Detect Changes to Composer Lock Files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: 'shell'
          filters: |
            composer-lock:
              - modified: './composer.lock'
              - modified: './utils/**/composer.lock'

      # see: https://github.com/dorny/paths-filter?tab=readme-ov-file#custom-processing-of-changed-files
      # filter "composer-lock" with 'list-files' option results in an output: "composer-lock_files"
      - name: Get changed directories
        id: parse-working-directories
        shell: bash
        run: |
          files="${{ steps.filter.outputs.composer-lock_files }}"
          dirs=$(echo "$files" | tr ' ' '\n' | xargs dirname | sort -u)
          json=$(printf '%s\n' "$dirs" | jq -R -s -c 'split("\n") | map(select(length > 0))')

          echo "directories=$json" >> $GITHUB_OUTPUT

  comment-composer-lock-diff:
    needs: composer-lock-directories
    if: ${{ needs.composer-lock-directories.outputs.directories != '[]' }}
    name: Comment composer.lock diff
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        working-directory: ${{ fromJson(needs.composer-lock-directories.outputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Comment composer.lock diff
        uses: WyriHaximus/github-action-composer.lock-diff@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          workingDirectory: ${{ matrix.working-directory }}
